# Generated by Django 4.1.3 on 2022-11-19 21:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expire_at", models.DateTimeField()),
                ("ciphertext", models.TextField(blank=True, null=True)),
                ("tag", models.TextField(blank=True, null=True)),
                ("is_viewed", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
